// Pre-encoded commander configurations
// Format: key -> encoded config string for quick sharing

export const COMMANDER_CONFIGS: Record<string, string> = {
  'israel': 'N4IgdghgtgpiBcJCLoIfdAAEgN0EJugWkgDQgBOEYA1giIBeggh6CAvoCgSAA4xEDOA9pADYByAVygAjNpQCsADnEA2AJziALE3YBLAOaQALgKIwAygDd1lADztjaAB5QeYdgF4AOiAAWWrc3gB6bwHcAgDo_AGZAziJ1bwAmAAZ47wt1FzQ_VQATLVdnEEV4lNcYDXccgEY4lwA-JzBTZggstHScgFloxQB2QJlZaPF8TsDoyXLxNAAZdrCemT6BmSGRvon2xW7e_sUF4dGVrfXZzbWd5cnxUoO5xQuTsbPJS_6QrtuVmS6ZuZCw18mO8Ue-BCsUWu0mkmigOiLyWd2Gcih21hKwUiNBp2BF0-_WiSLBwI-G3w0PRdxCpWmROBpIm5IW2KBAN-5IRDJCCOZ0SxRMUx2R4xC0UphwGHP5guFcyUNIFQsB4jF-LlDJkfKVkv68hlEsBHUhnMhDI6eIxcV1ioxpQeDJG2tK9KJkjVlrWNpNZIpgMkD2Z5S9PvFpW5Iu92tirMdAfxsWtkbDhJDUYxsQdibDrrjzNiwbm0hl0TkCdzN35BY1-A6SbhkgjIv--bzRv1pdtRpBv2hsZFWo79ZVVZWesBMgHky1_fzquHFrhUl1TNL4hBNubYNW_vz7MBchLa5CGZFqI71IZhfzuO3M5W7UBpXi54Pczvu9O0RvDLv7dLfW3MLXJNPVdX0FL1nThEIASNP9gNrOYhw7RRDSJHtS0GFVoNncseknHNNTAwckO7H4W0fTViLXOQuzmGRyJdYdaLJb56O1JdmOZbCVRfMkOlI_AFW1VsiXEDDaUkctZAE3jxAXfExPlGSMQheSBNwviFPEFJ2C0IhODIGAcmEHgIAAYzITTtN0mAAFo0kybIXGiFIADNVB4HgcjAbgYHMnS9KsnhVDAGBjIgZgch0gQwHSHzLP8wKYAAK04QLws4SLopAbxqlqRJjEqJhWDAABhTgeAiShDJMihCCc7gtH0LQAE8eDgRAiAEYRVAoABfIA',
}

export function getCommanderConfig(key: string): string | undefined {
  return COMMANDER_CONFIGS[key.toLowerCase()]
}
